# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        args:
          - --ini
          - setup.cfg
        exclude: tests/
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.0
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==21.5b2
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-blind-except
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-debugger
          - flake8-docstrings
          - flake8-isort
          - flake8-polyfill
          - flake8-pytest
          - flake8-quotes
          - flake8-typing-imports
          - yesqa
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: rst-backticks
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
        args:
          - --py37-plus
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: f6f816c65d285f8a4a15e0e9965b3dd66ecddd79
    hooks:
      - id: mypy
        args:
          - --show-error-codes
  - repo: https://github.com/PyCQA/pylint
    # - repo: local
    rev: v2.12.2
    hooks:
      - id: pylint
        name: pylint
        language: system
        exclude: tests/
        types:
          - python
  - repo: https://github.com/myint/autoflake
    rev: 3c3b2a2274e40a03d3d8f14815509662e9f454e0
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --remove-duplicate-keys
          - --ignore-init-module-imports
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: ea782651a7e32f40a3d13b76c79d5a2474ee8723
    hooks:
      - id: prettier
        stages:
          - commit
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 71d2d58c76c71551d4dba97bd432eb7786f45c86
    hooks:
      - id: commitizen
        stages:
          - commit-msg
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/openstack/bashate
    rev: 0feb84a83fca92789d2a154b33b959ef6ffbff11
    hooks:
      - id: bashate
        args:
          - -i
          - E006
